# Adopt a Buddy
# Hackerearth competition

In [3]:
import pandas as pd
import numpy as np
import xgboost as xgb

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from datetime import date

C:\Users\user\Anaconda3\envs\HC#7062_stage1\lib\site-packages\distributed\utils.py:134: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [WinError 10065] A socket operation was attempted to an unreachable host
  % (host, default, e), RuntimeWarning)

In [14]:
dataset = pd.read_csv('./a01c26dcd27711ea/Dataset/train.csv')
dataset.sort_values('breed_category')

,pet_id,issue_date,listing_date,condition,color_type,length(m),height(cm),X1,X2,breed_category,pet_category
0,ANSL_69903,2016-07-10 00:00:00,2016-09-21 16:25:00,2.0,Brown Tabby,0.80,7.78,13,9,0.0,1
14615,ANSL_56232,2017-12-09 00:00:00,2018-03-09 14:57:00,1.0,Brown Tabby,0.39,9.98,0,1,0.0,1
7444,ANSL_58335,2013-11-27 00:00:00,2016-12-19 11:40:00,2.0,Gray,0.49,17.51,13,9,0.0,2
14614,ANSL_67807,2011-12-14 00:00:00,2017-01-15 16:33:00,1.0,Brown,0.36,37.99,13,9,0.0,2
7446,ANSL_68616,2015-11-30 00:00:00,2016-11-21 17:49:00,1.0,Black,0.93,30.04,0,7,0.0,2
7447,ANSL_61696,2014-03-20 00:00:00,2018-11-12 18:37:00,1.0,Tan,0.13,10.99,0,7,0.0,2
7450,ANSL_55314,2016-05-17 00:00:00,2018-06-14 17:38:00,1.0,Brown Brindle,0.22,21.96,0,7,0.0,2
7452,ANSL_72228,2013-08-17 00:00:00,2016-09-17 11:39:00,1.0,White,0.14,28.68,0,7,0.0,2
14616,ANSL_53663,2016-11-16 00:00:00,2017-02-15 13:54:00,2.0,Brown Tabby,0.51,31.83,13,9,0.0,1
7454,ANSL_59197,2014-01-07 00:00:00,2019-03-19 16:41:00,1.0,Blue Merle,0.67,9.57,0,1,0.0,2
14608,ANSL_68552,2017-07-13 00:00:00,2017-11-03 09:00:00,2.0,Orange Tabby,0.38,10.35,16,9,0.0,1
14607,ANSL_53373,2016-12-14 00:00:00,2018-07-08 18:15:00,1.0,Tan,0.23,23.73,0,1,0.0,2
14606,ANSL_65681,2013-05-11 00:00:00,2018-06-06 15:33:00,1.0,Black,0.84,10.46,0,1,0.0,1
14605,ANSL_60527,2011-12-28 00:00:00,2017-10-21 11:38:00,1.0,Brown,0.14,8.18,0,7,0.0,2
14603,ANSL_57456,2014-04-29 00:00:00,2017-06-20 16:37:00,2.0,Black,0.32,16.75,0,7,0.0,2
14601,ANSL_51542,2017-07-06 00:00:00,2018-07-26 17:32:00,2.0,White,0.91,11.91,13,9,0.0,2
7463,ANSL_60476,2018-08-13 00:00:00,2018-10-23 00:00:00,2.0,Orange Tabby,0.17,42.66,13,9,0.0,1
7455,ANSL_53636,2016-02-12 00:00:00,2017-03-10 13:57:00,1.0,Brown Brindle,0.15,24.68,13,9,0.0,2
7464,ANSL_59909,2016-07-02 00:00:00,2016-10-03 18:29:00,1.0,Black Brindle,0.99,13.41,0,1,0.0,2
7440,ANSL_60091,2017-11-29 00:00:00,2018-12-20 11:53:00,1.0,Brown Brindle,0.88,16.14,0,7,0.0,2
7438,ANSL_70763,2015-12-20 00:00:00,2016-12-31 18:39:00,1.0,Tan,0.04,28.97,0,1,0.0,2
14631,ANSL_68745,2016-05-22 00:00:00,2017-12-12 19:15:00,2.0,White,0.25,34.31,0,7,0.0,2
7418,ANSL_67663,2016-09-30 00:00:00,2017-02-23 14:00:00,1.0,White,0.11,8.81,7,1,0.0,1
14629,ANSL_70569,2016-11-15 00:00:00,2018-02-14 17:20:00,1.0,Tan,0.19,45.90,0,1,0.0,2
7422,ANSL_68419,2016-08-25 00:00:00,2017-09-18 17:34:00,1.0,Brown Brindle,0.41,38.42,0,7,0.0,2
7423,ANSL_63724,2015-07-08 00:00:00,2016-07-29 09:00:00,2.0,Brown Tabby,0.15,40.17,16,9,0.0,1
7424,ANSL_64690,2017-06-08 00:00:00,2017-08-24 14:01:00,2.0,Lynx Point,0.72,17.39,13,9,0.0,1
14627,ANSL_59108,2010-08-16 00:00:00,2017-09-08 15:09:00,1.0,Tan,0.64,7.61,0,1,0.0,2
14618,ANSL_50850,2016-11-10 00:00:00,2018-12-08 18:55:00,1.0,White,0.41,34.34,0,8,0.0,2
7426,ANSL_69718,2018-10-20 00:00:00,2018-12-24 13:13:00,2.0,Orange Tabby,0.23,49.58,18,4,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...
2521,ANSL_73054,2016-09-19 00:00:00,2017-04-09 19:21:00,NaN,Brown,0.89,8.15,15,4,2.0,4
10077,ANSL_57877,2017-01-09 00:00:00,2019-01-30 11:43:00,NaN,Black,0.17,18.28,15,4,2.0,1
10081,ANSL_66022,2016-12-04 00:00:00,2017-06-24 17:11:00,NaN,Brown,0.01,15.47,15,4,2.0,4
17477,ANSL_52467,2018-08-11 00:00:00,2018-10-02 18:26:00,NaN,Torbie,0.34,26.25,18,4,2.0,1
15863,ANSL_65960,2015-11-04 00:00:00,2017-11-25 17:00:00,NaN,Brown,0.28,48.60,15,4,2.0,4
13121,ANSL_61740,2017-02-11 00:00:00,2018-03-04 16:46:00,NaN,Brown,0.63,48.02,15,4,2.0,4
17474,ANSL_65143,2016-05-31 00:00:00,2016-12-21 09:18:00,NaN,Brown,0.50,49.40,18,4,2.0,4
5255,ANSL_70126,2016-10-18 00:00:00,2017-06-19 18:58:00,NaN,Tortie,0.18,15.73,16,9,2.0,1
15866,ANSL_64955,2016-03-18 00:00:00,2018-04-10 13:04:00,NaN,Gray,0.53,14.29,0,1,2.0,0
10124,ANSL_55517,2015-06-09 00:00:00,2017-06-30 17:35:00,NaN,Brown,0.40,22.46,0,3,2.0,4
7842,ANSL_52047,2017-09-17 00:00:00,2017-10-08 11:33:00,NaN,Brown Tabby,0.89,42.59,13,9,2.0,1
10118,ANSL_65365,2017-06-05 00:00:00,2018-06-27 08:39:00,NaN,Brown,0.76,27.00,15,4,2.0,4
17465,ANSL_58699,2017-07-05 00:00:00,2017-08-09 17:52:00,NaN,Black Tabby,0.65,23.40,13,9,2.0,1
5240,ANSL_68284,2015-06-13 00:00:00,2017-07-05 09:49:00,NaN,Brown,0.82,10.16,15,4,2.0,4
2461,ANSL_76743,2017-04-19 00:00:00,2019-05-10 08:43:00,NaN,Brown,0.90,48.75,15,4,2.0,4
14381,ANSL_65728,2018-09-26 00:00:00,2019-01-19 19:37:00,NaN,Blue Merle,0.32,45.76,13,9,2.0,2
2472,ANSL_61972,2017-06-21 00:00:00,2018-07-12 09:21:00,NaN,Brown,0.27,40.52,15,4,2.0,4
17455,ANSL_53589,2016-11-25 00:00:00,2017-12-16 08:37:00,NaN,Black,0.30,5.75,15,4,2.0,4
13137,ANSL_72580,2008-10-07 00:00:00,2018-10-27 00:00:00,NaN,White,0.76,28.62,13,9,2.0,2
15878,ANSL_70722,2016-06-12 00:00:00,2017-07-03 16:20:00,NaN,Brown,0.48,46.56,0,3,2.0,4
17451,ANSL_56557,2017-02-03 00:00:00,2017-08-24 12:30:00,NaN,Brown,0.18,39.53,15,4,2.0,4
7858,ANSL_56313,2014-08-06 00:00:00,2017-08-27 12:23:00,NaN,White,0.32,40.79,11,4,2.0,4
2489,ANSL_66850,2018-07-02 00:00:00,2018-07-25 14:15:00,NaN,Cream,0.96,16.43,9,2,2.0,1
7861,ANSL_76152,2018-04-04 00:00:00,2019-04-27 08:48:00,NaN,Brown,0.42,14.55,15,4,2.0,4
5211,ANSL_73382,2015-06-09 00:00:00,2017-06-30 17:36:00,NaN,Gray,0.82,19.62,15,4,2.0,4
10086,ANSL_50575,2016-06-17 00:00:00,2016-07-29 13:46:00,NaN,Black,0.45,31.25,18,4,2.0,1
15886,ANSL_62791,2016-01-07 00:00:00,2017-01-28 16:56:00,NaN,Red,0.36,11.08,15,4,2.0,4
5209,ANSL_62541,2018-02-25 00:00:00,2018-09-15 14:17:00,NaN,Brown,0.24,28.64,11,4,2.0,4
2433,ANSL_68330,2018-03-17 00:00:00,2018-10-07 11:22:00,NaN,Orange,0.18,43.53,13,9,2.0,4
15036,ANSL_69501,2017-05-23 00:00:00,2017-12-15 11:49:00,NaN,Buff,0.42,10.52,13,9,2.0,2

In [ ]:
'''
Traning Dataset discription:
in_features: 6
no_samples: 18834
out_features: 2 // predict

'''

In [64]:
# Extact input features as a np array
in_features = ['issue_date','listing_date','condition', 'color_type', 'length(m)', 'height(cm)','X1','X2']
x = np.array(dataset[in_features])
print(x)

x[0,0]

[['2016-07-10 00:00:00' '2016-09-21 16:25:00' 2.0 ... 7.78 13 9]
 ['2013-11-21 00:00:00' '2018-12-27 17:47:00' 1.0 ... 14.19 13 9]
 ['2014-09-28 00:00:00' '2016-10-19 08:24:00' nan ... 40.9 15 4]
 ...
 ['2010-07-21 00:00:00' '2018-08-22 14:27:00' 0.0 ... 28.13 13 9]
 ['2017-05-12 00:00:00' '2018-02-08 14:05:00' 0.0 ... 44.82 13 9]
 ['2011-12-13 00:00:00' '2018-10-26 14:18:00' 0.0 ... 37.4 0 1]]

'2016-07-10 00:00:00'

In [32]:
out_features = ['breed_category', 'pet_category']
y = np.array(dataset[out_features])
y

array([[0., 1.],
       [0., 2.],
       [2., 4.],
       ...,
       [1., 1.],
       [1., 2.],
       [1., 2.]])

In [13]:
pet_category = {'0':0,'1':0,'2':0,'3':0,'4':0}
breed_category = {'0':0,'1':0,'2':0}

for f in range(0,len(dataset)):
    if (dataset['pet_category'][f] == 0):
        pet_category['0'] +=1
    if (dataset['pet_category'][f] == 1):
        pet_category['1'] +=1
    if (dataset['pet_category'][f] == 2):
        pet_category['2'] +=1
    if (dataset['pet_category'][f] == 3):
        pet_category['3'] +=1
    if (dataset['pet_category'][f] == 4):
        pet_category['4'] +=1
        
#It shows us distribution of each fruit in given dataset
#we printed no of images that a single type of fruit have in given dataset
print(' 0 : ',pet_category['0'],' 1 : ', pet_category['1'], '2 : ',pet_category['2'],
      ' 3 :',pet_category['3'],' 4 : ',pet_category['4'])

 0 :  88  1 :  7184 2 :  10621  3 : 0  4 :  941